#!/usr/bin/env node
// Copyright (c) 2010-2012 Robert Kieffer

var argv = require('minimist')(process.argv.slice(2));
var fs = require('fs');
var Sectionify = require('./index.js');

// main
var input = argv._.shift();
var output = process.stdout;

var stream = new Sectionify.Stream(argv._);

if (argv.header) {
  output.write(argv.header);
}

fs.createReadStream(input).pipe(stream).pipe(output);
